/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
					put(grammarAccess.getPagePrincipaleAccess().getGroup(), "rule__PagePrincipale__Group__0");
					put(grammarAccess.getPagePrincipaleAccess().getGroup_5(), "rule__PagePrincipale__Group_5__0");
					put(grammarAccess.getPagePrincipaleAccess().getGroup_7(), "rule__PagePrincipale__Group_7__0");
					put(grammarAccess.getPagePrincipaleAccess().getGroup_8(), "rule__PagePrincipale__Group_8__0");
					put(grammarAccess.getPagePrincipaleAccess().getGroup_8_3(), "rule__PagePrincipale__Group_8_3__0");
					put(grammarAccess.getPagePrincipaleAccess().getGroup_14(), "rule__PagePrincipale__Group_14__0");
					put(grammarAccess.getContactAccess().getGroup(), "rule__Contact__Group__0");
					put(grammarAccess.getContactAccess().getGroup_3(), "rule__Contact__Group_3__0");
					put(grammarAccess.getContactAccess().getGroup_4(), "rule__Contact__Group_4__0");
					put(grammarAccess.getContactAccess().getGroup_5(), "rule__Contact__Group_5__0");
					put(grammarAccess.getContactAccess().getGroup_6(), "rule__Contact__Group_6__0");
					put(grammarAccess.getContactAccess().getGroup_7(), "rule__Contact__Group_7__0");
					put(grammarAccess.getRubriquesAccess().getGroup(), "rule__Rubriques__Group__0");
					put(grammarAccess.getRubriquesAccess().getGroup_3(), "rule__Rubriques__Group_3__0");
					put(grammarAccess.getRubriquesAccess().getGroup_4(), "rule__Rubriques__Group_4__0");
					put(grammarAccess.getFichiersAccess().getGroup(), "rule__Fichiers__Group__0");
					put(grammarAccess.getFichiersAccess().getGroup_3(), "rule__Fichiers__Group_3__0");
					put(grammarAccess.getFichiersAccess().getGroup_4(), "rule__Fichiers__Group_4__0");
					put(grammarAccess.getFichiersAccess().getGroup_5(), "rule__Fichiers__Group_5__0");
					put(grammarAccess.getFichiersAccess().getGroup_6(), "rule__Fichiers__Group_6__0");
					put(grammarAccess.getConfigurationPageAccess().getGroup(), "rule__ConfigurationPage__Group__0");
					put(grammarAccess.getConfigurationPageAccess().getGroup_3(), "rule__ConfigurationPage__Group_3__0");
					put(grammarAccess.getConfigurationPageAccess().getGroup_4(), "rule__ConfigurationPage__Group_4__0");
					put(grammarAccess.getConfigurationPageAccess().getGroup_5(), "rule__ConfigurationPage__Group_5__0");
					put(grammarAccess.getConfigurationPageAccess().getGroup_6(), "rule__ConfigurationPage__Group_6__0");
					put(grammarAccess.getConfigurationPageAccess().getGroup_7(), "rule__ConfigurationPage__Group_7__0");
					put(grammarAccess.getPageInterneAccess().getGroup(), "rule__PageInterne__Group__0");
					put(grammarAccess.getPageInterneAccess().getGroup_2(), "rule__PageInterne__Group_2__0");
					put(grammarAccess.getPageInterneAccess().getGroup_3(), "rule__PageInterne__Group_3__0");
					put(grammarAccess.getPageInterneAccess().getGroup_4(), "rule__PageInterne__Group_4__0");
					put(grammarAccess.getPageInterneAccess().getGroup_5(), "rule__PageInterne__Group_5__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getTypesAccess().getGroup(), "rule__Types__Group__0");
					put(grammarAccess.getLiensAccess().getGroup(), "rule__Liens__Group__0");
					put(grammarAccess.getLiensAccess().getGroup_3(), "rule__Liens__Group_3__0");
					put(grammarAccess.getLiensAccess().getGroup_4(), "rule__Liens__Group_4__0");
					put(grammarAccess.getLiensAccess().getGroup_5(), "rule__Liens__Group_5__0");
					put(grammarAccess.getPhotoAccess().getGroup(), "rule__Photo__Group__0");
					put(grammarAccess.getPhotoAccess().getGroup_3(), "rule__Photo__Group_3__0");
					put(grammarAccess.getPhotoAccess().getGroup_4(), "rule__Photo__Group_4__0");
					put(grammarAccess.getPhotoAccess().getGroup_5(), "rule__Photo__Group_5__0");
					put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
					put(grammarAccess.getPagePrincipaleAccess().getContactsAssignment_4(), "rule__PagePrincipale__ContactsAssignment_4");
					put(grammarAccess.getPagePrincipaleAccess().getContactsAssignment_5_1(), "rule__PagePrincipale__ContactsAssignment_5_1");
					put(grammarAccess.getPagePrincipaleAccess().getRubriquesAssignment_7_1(), "rule__PagePrincipale__RubriquesAssignment_7_1");
					put(grammarAccess.getPagePrincipaleAccess().getFichiersAssignment_8_2(), "rule__PagePrincipale__FichiersAssignment_8_2");
					put(grammarAccess.getPagePrincipaleAccess().getFichiersAssignment_8_3_1(), "rule__PagePrincipale__FichiersAssignment_8_3_1");
					put(grammarAccess.getPagePrincipaleAccess().getConfigurationPageAssignment_10(), "rule__PagePrincipale__ConfigurationPageAssignment_10");
					put(grammarAccess.getPagePrincipaleAccess().getPagesAssignment_13(), "rule__PagePrincipale__PagesAssignment_13");
					put(grammarAccess.getPagePrincipaleAccess().getPagesAssignment_14_1(), "rule__PagePrincipale__PagesAssignment_14_1");
					put(grammarAccess.getContactAccess().getNomAssignment_3_1(), "rule__Contact__NomAssignment_3_1");
					put(grammarAccess.getContactAccess().getPrenomAssignment_4_1(), "rule__Contact__PrenomAssignment_4_1");
					put(grammarAccess.getContactAccess().getAdresseAssignment_5_1(), "rule__Contact__AdresseAssignment_5_1");
					put(grammarAccess.getContactAccess().getMailAssignment_6_1(), "rule__Contact__MailAssignment_6_1");
					put(grammarAccess.getContactAccess().getTelephoneAssignment_7_1(), "rule__Contact__TelephoneAssignment_7_1");
					put(grammarAccess.getRubriquesAccess().getTexteAssignment_3_1(), "rule__Rubriques__TexteAssignment_3_1");
					put(grammarAccess.getRubriquesAccess().getLienAssignment_4_1(), "rule__Rubriques__LienAssignment_4_1");
					put(grammarAccess.getFichiersAccess().getTypeAssignment_3_1(), "rule__Fichiers__TypeAssignment_3_1");
					put(grammarAccess.getFichiersAccess().getTailleAssignment_4_1(), "rule__Fichiers__TailleAssignment_4_1");
					put(grammarAccess.getFichiersAccess().getNomAssignment_5_1(), "rule__Fichiers__NomAssignment_5_1");
					put(grammarAccess.getFichiersAccess().getEmplacementAssignment_6_1(), "rule__Fichiers__EmplacementAssignment_6_1");
					put(grammarAccess.getConfigurationPageAccess().getCouleurFondAssignment_3_1(), "rule__ConfigurationPage__CouleurFondAssignment_3_1");
					put(grammarAccess.getConfigurationPageAccess().getTitreSiteAssignment_4_1(), "rule__ConfigurationPage__TitreSiteAssignment_4_1");
					put(grammarAccess.getConfigurationPageAccess().getAuteursAssignment_5_1(), "rule__ConfigurationPage__AuteursAssignment_5_1");
					put(grammarAccess.getConfigurationPageAccess().getCouleurPoliceAssignment_6_1(), "rule__ConfigurationPage__CouleurPoliceAssignment_6_1");
					put(grammarAccess.getConfigurationPageAccess().getTaillePoliceAssignment_7_1(), "rule__ConfigurationPage__TaillePoliceAssignment_7_1");
					put(grammarAccess.getPageInterneAccess().getTitrePageAssignment_2_1(), "rule__PageInterne__TitrePageAssignment_2_1");
					put(grammarAccess.getPageInterneAccess().getTexteAssignment_3_1(), "rule__PageInterne__TexteAssignment_3_1");
					put(grammarAccess.getPageInterneAccess().getTypesAssignment_4_1(), "rule__PageInterne__TypesAssignment_4_1");
					put(grammarAccess.getPageInterneAccess().getLiensAssignment_5_1(), "rule__PageInterne__LiensAssignment_5_1");
					put(grammarAccess.getPageInterneAccess().getPhotoAssignment_7(), "rule__PageInterne__PhotoAssignment_7");
					put(grammarAccess.getTypesAccess().getGrasAssignment_1(), "rule__Types__GrasAssignment_1");
					put(grammarAccess.getTypesAccess().getItaliqueAssignment_2(), "rule__Types__ItaliqueAssignment_2");
					put(grammarAccess.getLiensAccess().getFichierAssignment_3_1(), "rule__Liens__FichierAssignment_3_1");
					put(grammarAccess.getLiensAccess().getAdresseWebAssignment_4_1(), "rule__Liens__AdresseWebAssignment_4_1");
					put(grammarAccess.getLiensAccess().getPageInterneAssignment_5_1(), "rule__Liens__PageInterneAssignment_5_1");
					put(grammarAccess.getPhotoAccess().getTailleAssignment_3_1(), "rule__Photo__TailleAssignment_3_1");
					put(grammarAccess.getPhotoAccess().getExtensionAssignment_4_1(), "rule__Photo__ExtensionAssignment_4_1");
					put(grammarAccess.getPhotoAccess().getNomAssignment_5_1(), "rule__Photo__NomAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRulePagePrincipale();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
