/*
 * generated by Xtext
 */
package org.xtext.example.siteWeb;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.xtext.example.siteWeb.AbstractMyDslRuntimeModule {

}
