/*
* generated by Xtext
*/
package org.xtext.example.siteWeb.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class PagePrincipaleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PagePrincipale");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPagePrincipaleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConfigurationPageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConfigurationPageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConfigurationPageConfigurationPageParserRuleCall_3_0 = (RuleCall)cConfigurationPageAssignment_3.eContents().get(0);
		private final Keyword cContactsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cContactsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cContactsContactParserRuleCall_6_0 = (RuleCall)cContactsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cContactsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cContactsContactParserRuleCall_7_1_0 = (RuleCall)cContactsAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cPagesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cPagesAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cPagesPageInterneParserRuleCall_11_0 = (RuleCall)cPagesAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cPagesAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cPagesPageInterneParserRuleCall_12_1_0 = (RuleCall)cPagesAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cRubriquesKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cRubriquesAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cRubriquesRubriquesParserRuleCall_14_1_0 = (RuleCall)cRubriquesAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cFichiersKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cFichiersAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final RuleCall cFichiersFichiersParserRuleCall_15_2_0 = (RuleCall)cFichiersAssignment_15_2.eContents().get(0);
		private final Group cGroup_15_3 = (Group)cGroup_15.eContents().get(3);
		private final Keyword cCommaKeyword_15_3_0 = (Keyword)cGroup_15_3.eContents().get(0);
		private final Assignment cFichiersAssignment_15_3_1 = (Assignment)cGroup_15_3.eContents().get(1);
		private final RuleCall cFichiersFichiersParserRuleCall_15_3_1_0 = (RuleCall)cFichiersAssignment_15_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15_4 = (Keyword)cGroup_15.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//PagePrincipale:
		//	"PagePrincipale" "{" "configurationPage" configurationPage=ConfigurationPage "contacts" "{" contacts+=Contact (","
		//	contacts+=Contact)* "}" "pages" "{" pages+=PageInterne ("," pages+=PageInterne)* "}" ("rubriques"
		//	rubriques=Rubriques)? ("fichiers" "{" fichiers+=Fichiers ("," fichiers+=Fichiers)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"PagePrincipale" "{" "configurationPage" configurationPage=ConfigurationPage "contacts" "{" contacts+=Contact (","
		//contacts+=Contact)* "}" "pages" "{" pages+=PageInterne ("," pages+=PageInterne)* "}" ("rubriques"
		//rubriques=Rubriques)? ("fichiers" "{" fichiers+=Fichiers ("," fichiers+=Fichiers)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"PagePrincipale"
		public Keyword getPagePrincipaleKeyword_0() { return cPagePrincipaleKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"configurationPage"
		public Keyword getConfigurationPageKeyword_2() { return cConfigurationPageKeyword_2; }

		//configurationPage=ConfigurationPage
		public Assignment getConfigurationPageAssignment_3() { return cConfigurationPageAssignment_3; }

		//ConfigurationPage
		public RuleCall getConfigurationPageConfigurationPageParserRuleCall_3_0() { return cConfigurationPageConfigurationPageParserRuleCall_3_0; }

		//"contacts"
		public Keyword getContactsKeyword_4() { return cContactsKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//contacts+=Contact
		public Assignment getContactsAssignment_6() { return cContactsAssignment_6; }

		//Contact
		public RuleCall getContactsContactParserRuleCall_6_0() { return cContactsContactParserRuleCall_6_0; }

		//("," contacts+=Contact)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//contacts+=Contact
		public Assignment getContactsAssignment_7_1() { return cContactsAssignment_7_1; }

		//Contact
		public RuleCall getContactsContactParserRuleCall_7_1_0() { return cContactsContactParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"pages"
		public Keyword getPagesKeyword_9() { return cPagesKeyword_9; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }

		//pages+=PageInterne
		public Assignment getPagesAssignment_11() { return cPagesAssignment_11; }

		//PageInterne
		public RuleCall getPagesPageInterneParserRuleCall_11_0() { return cPagesPageInterneParserRuleCall_11_0; }

		//("," pages+=PageInterne)*
		public Group getGroup_12() { return cGroup_12; }

		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }

		//pages+=PageInterne
		public Assignment getPagesAssignment_12_1() { return cPagesAssignment_12_1; }

		//PageInterne
		public RuleCall getPagesPageInterneParserRuleCall_12_1_0() { return cPagesPageInterneParserRuleCall_12_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }

		//("rubriques" rubriques=Rubriques)?
		public Group getGroup_14() { return cGroup_14; }

		//"rubriques"
		public Keyword getRubriquesKeyword_14_0() { return cRubriquesKeyword_14_0; }

		//rubriques=Rubriques
		public Assignment getRubriquesAssignment_14_1() { return cRubriquesAssignment_14_1; }

		//Rubriques
		public RuleCall getRubriquesRubriquesParserRuleCall_14_1_0() { return cRubriquesRubriquesParserRuleCall_14_1_0; }

		//("fichiers" "{" fichiers+=Fichiers ("," fichiers+=Fichiers)* "}")?
		public Group getGroup_15() { return cGroup_15; }

		//"fichiers"
		public Keyword getFichiersKeyword_15_0() { return cFichiersKeyword_15_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_15_1() { return cLeftCurlyBracketKeyword_15_1; }

		//fichiers+=Fichiers
		public Assignment getFichiersAssignment_15_2() { return cFichiersAssignment_15_2; }

		//Fichiers
		public RuleCall getFichiersFichiersParserRuleCall_15_2_0() { return cFichiersFichiersParserRuleCall_15_2_0; }

		//("," fichiers+=Fichiers)*
		public Group getGroup_15_3() { return cGroup_15_3; }

		//","
		public Keyword getCommaKeyword_15_3_0() { return cCommaKeyword_15_3_0; }

		//fichiers+=Fichiers
		public Assignment getFichiersAssignment_15_3_1() { return cFichiersAssignment_15_3_1; }

		//Fichiers
		public RuleCall getFichiersFichiersParserRuleCall_15_3_1_0() { return cFichiersFichiersParserRuleCall_15_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15_4() { return cRightCurlyBracketKeyword_15_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}

	public class ContactElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Contact");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cContactAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cContactKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNomKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNomAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNomEStringParserRuleCall_3_1_0 = (RuleCall)cNomAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPrenomKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPrenomAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPrenomEStringParserRuleCall_4_1_0 = (RuleCall)cPrenomAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAdresseKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAdresseAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAdresseEStringParserRuleCall_5_1_0 = (RuleCall)cAdresseAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMailKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMailAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cMailEStringParserRuleCall_6_1_0 = (RuleCall)cMailAssignment_6_1.eContents().get(0);
		private final Keyword cCommercialAtKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final RuleCall cEStringParserRuleCall_6_3 = (RuleCall)cGroup_6.eContents().get(3);
		private final Keyword cFullStopKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final RuleCall cEStringParserRuleCall_6_5 = (RuleCall)cGroup_6.eContents().get(5);
		private final RuleCall cEStringParserRuleCall_6_6 = (RuleCall)cGroup_6.eContents().get(6);
		private final RuleCall cEStringParserRuleCall_6_7 = (RuleCall)cGroup_6.eContents().get(7);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTelephoneKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTelephoneAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTelephoneEStringParserRuleCall_7_1_0 = (RuleCall)cTelephoneAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Contact:
		//	{Contact} "Contact" "{" ("nom : " nom=EString)? ("prenom : " prenom=EString)? ("adresse : " adresse=EString)?
		//	("mail : " mail=EString+ "@" EString+ "." EString EString EString) ("telephone : " telephone=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Contact} "Contact" "{" ("nom : " nom=EString)? ("prenom : " prenom=EString)? ("adresse : " adresse=EString)? ("mail : "
		//mail=EString+ "@" EString+ "." EString EString EString) ("telephone : " telephone=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Contact}
		public Action getContactAction_0() { return cContactAction_0; }

		//"Contact"
		public Keyword getContactKeyword_1() { return cContactKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("nom : " nom=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"nom : "
		public Keyword getNomKeyword_3_0() { return cNomKeyword_3_0; }

		//nom=EString
		public Assignment getNomAssignment_3_1() { return cNomAssignment_3_1; }

		//EString
		public RuleCall getNomEStringParserRuleCall_3_1_0() { return cNomEStringParserRuleCall_3_1_0; }

		//("prenom : " prenom=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"prenom : "
		public Keyword getPrenomKeyword_4_0() { return cPrenomKeyword_4_0; }

		//prenom=EString
		public Assignment getPrenomAssignment_4_1() { return cPrenomAssignment_4_1; }

		//EString
		public RuleCall getPrenomEStringParserRuleCall_4_1_0() { return cPrenomEStringParserRuleCall_4_1_0; }

		//("adresse : " adresse=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"adresse : "
		public Keyword getAdresseKeyword_5_0() { return cAdresseKeyword_5_0; }

		//adresse=EString
		public Assignment getAdresseAssignment_5_1() { return cAdresseAssignment_5_1; }

		//EString
		public RuleCall getAdresseEStringParserRuleCall_5_1_0() { return cAdresseEStringParserRuleCall_5_1_0; }

		//"mail : " mail=EString+ "@" EString+ "." EString EString EString
		public Group getGroup_6() { return cGroup_6; }

		//"mail : "
		public Keyword getMailKeyword_6_0() { return cMailKeyword_6_0; }

		//mail=EString+
		public Assignment getMailAssignment_6_1() { return cMailAssignment_6_1; }

		//EString
		public RuleCall getMailEStringParserRuleCall_6_1_0() { return cMailEStringParserRuleCall_6_1_0; }

		//"@"
		public Keyword getCommercialAtKeyword_6_2() { return cCommercialAtKeyword_6_2; }

		//EString+
		public RuleCall getEStringParserRuleCall_6_3() { return cEStringParserRuleCall_6_3; }

		//"."
		public Keyword getFullStopKeyword_6_4() { return cFullStopKeyword_6_4; }

		//EString
		public RuleCall getEStringParserRuleCall_6_5() { return cEStringParserRuleCall_6_5; }

		//EString
		public RuleCall getEStringParserRuleCall_6_6() { return cEStringParserRuleCall_6_6; }

		//EString
		public RuleCall getEStringParserRuleCall_6_7() { return cEStringParserRuleCall_6_7; }

		//("telephone : " telephone=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"telephone : "
		public Keyword getTelephoneKeyword_7_0() { return cTelephoneKeyword_7_0; }

		//telephone=EString
		public Assignment getTelephoneAssignment_7_1() { return cTelephoneAssignment_7_1; }

		//EString
		public RuleCall getTelephoneEStringParserRuleCall_7_1_0() { return cTelephoneEStringParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class RubriquesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rubriques");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRubriquesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRubriquesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTexteKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTexteAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTexteEStringParserRuleCall_3_1_0 = (RuleCall)cTexteAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLienKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLienAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLienEStringParserRuleCall_4_1_0 = (RuleCall)cLienAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Rubriques:
		//	{Rubriques} "Rubriques" "{" ("texte : " texte=EString)? ("lien : " lien=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Rubriques} "Rubriques" "{" ("texte : " texte=EString)? ("lien : " lien=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Rubriques}
		public Action getRubriquesAction_0() { return cRubriquesAction_0; }

		//"Rubriques"
		public Keyword getRubriquesKeyword_1() { return cRubriquesKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("texte : " texte=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"texte : "
		public Keyword getTexteKeyword_3_0() { return cTexteKeyword_3_0; }

		//texte=EString
		public Assignment getTexteAssignment_3_1() { return cTexteAssignment_3_1; }

		//EString
		public RuleCall getTexteEStringParserRuleCall_3_1_0() { return cTexteEStringParserRuleCall_3_1_0; }

		//("lien : " lien=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"lien : "
		public Keyword getLienKeyword_4_0() { return cLienKeyword_4_0; }

		//lien=EString
		public Assignment getLienAssignment_4_1() { return cLienAssignment_4_1; }

		//EString
		public RuleCall getLienEStringParserRuleCall_4_1_0() { return cLienEStringParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class FichiersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Fichiers");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFichiersAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFichiersKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTailleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTailleAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTailleEIntParserRuleCall_4_1_0 = (RuleCall)cTailleAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNomKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNomAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cNomEStringParserRuleCall_5_1_0 = (RuleCall)cNomAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEmplacementKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cEmplacementAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cEmplacementEStringParserRuleCall_6_1_0 = (RuleCall)cEmplacementAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Fichiers:
		//	{Fichiers} "Fichiers" "{" ("type : " type=EString)? ("taille : " taille=EInt)? ("nom : " nom=EString)?
		//	("emplacement : " emplacement=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Fichiers} "Fichiers" "{" ("type : " type=EString)? ("taille : " taille=EInt)? ("nom : " nom=EString)? ("emplacement : "
		//emplacement=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Fichiers}
		public Action getFichiersAction_0() { return cFichiersAction_0; }

		//"Fichiers"
		public Keyword getFichiersKeyword_1() { return cFichiersKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("type : " type=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"type : "
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }

		//type=EString
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_3_1_0() { return cTypeEStringParserRuleCall_3_1_0; }

		//("taille : " taille=EInt)?
		public Group getGroup_4() { return cGroup_4; }

		//"taille : "
		public Keyword getTailleKeyword_4_0() { return cTailleKeyword_4_0; }

		//taille=EInt
		public Assignment getTailleAssignment_4_1() { return cTailleAssignment_4_1; }

		//EInt
		public RuleCall getTailleEIntParserRuleCall_4_1_0() { return cTailleEIntParserRuleCall_4_1_0; }

		//("nom : " nom=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"nom : "
		public Keyword getNomKeyword_5_0() { return cNomKeyword_5_0; }

		//nom=EString
		public Assignment getNomAssignment_5_1() { return cNomAssignment_5_1; }

		//EString
		public RuleCall getNomEStringParserRuleCall_5_1_0() { return cNomEStringParserRuleCall_5_1_0; }

		//("emplacement : " emplacement=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"emplacement : "
		public Keyword getEmplacementKeyword_6_0() { return cEmplacementKeyword_6_0; }

		//emplacement=EString
		public Assignment getEmplacementAssignment_6_1() { return cEmplacementAssignment_6_1; }

		//EString
		public RuleCall getEmplacementEStringParserRuleCall_6_1_0() { return cEmplacementEStringParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ConfigurationPageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConfigurationPage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConfigurationPageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConfigurationPageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCouleurFondKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCouleurFondAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCouleurFondEStringParserRuleCall_3_1_0 = (RuleCall)cCouleurFondAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTitreSiteKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTitreSiteAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTitreSiteEStringParserRuleCall_4_1_0 = (RuleCall)cTitreSiteAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAuteursKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAuteursAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAuteursEStringParserRuleCall_5_1_0 = (RuleCall)cAuteursAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCouleurPoliceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCouleurPoliceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCouleurPoliceEStringParserRuleCall_6_1_0 = (RuleCall)cCouleurPoliceAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTaillePoliceKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cTaillePoliceAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cTaillePoliceEIntParserRuleCall_7_1_0 = (RuleCall)cTaillePoliceAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ConfigurationPage:
		//	{ConfigurationPage} "ConfigurationPage" "{" ("couleurFond : " couleurFond=EString)? ("titreSite : "
		//	titreSite=EString)? ("auteurs : " auteurs=EString)? ("couleurPolice : " couleurPolice=EString)? ("taillePolice : "
		//	taillePolice=EInt)? "}";
		public ParserRule getRule() { return rule; }

		//{ConfigurationPage} "ConfigurationPage" "{" ("couleurFond : " couleurFond=EString)? ("titreSite : " titreSite=EString)?
		//("auteurs : " auteurs=EString)? ("couleurPolice : " couleurPolice=EString)? ("taillePolice : " taillePolice=EInt)? "}"
		public Group getGroup() { return cGroup; }

		//{ConfigurationPage}
		public Action getConfigurationPageAction_0() { return cConfigurationPageAction_0; }

		//"ConfigurationPage"
		public Keyword getConfigurationPageKeyword_1() { return cConfigurationPageKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("couleurFond : " couleurFond=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"couleurFond : "
		public Keyword getCouleurFondKeyword_3_0() { return cCouleurFondKeyword_3_0; }

		//couleurFond=EString
		public Assignment getCouleurFondAssignment_3_1() { return cCouleurFondAssignment_3_1; }

		//EString
		public RuleCall getCouleurFondEStringParserRuleCall_3_1_0() { return cCouleurFondEStringParserRuleCall_3_1_0; }

		//("titreSite : " titreSite=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"titreSite : "
		public Keyword getTitreSiteKeyword_4_0() { return cTitreSiteKeyword_4_0; }

		//titreSite=EString
		public Assignment getTitreSiteAssignment_4_1() { return cTitreSiteAssignment_4_1; }

		//EString
		public RuleCall getTitreSiteEStringParserRuleCall_4_1_0() { return cTitreSiteEStringParserRuleCall_4_1_0; }

		//("auteurs : " auteurs=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"auteurs : "
		public Keyword getAuteursKeyword_5_0() { return cAuteursKeyword_5_0; }

		//auteurs=EString
		public Assignment getAuteursAssignment_5_1() { return cAuteursAssignment_5_1; }

		//EString
		public RuleCall getAuteursEStringParserRuleCall_5_1_0() { return cAuteursEStringParserRuleCall_5_1_0; }

		//("couleurPolice : " couleurPolice=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"couleurPolice : "
		public Keyword getCouleurPoliceKeyword_6_0() { return cCouleurPoliceKeyword_6_0; }

		//couleurPolice=EString
		public Assignment getCouleurPoliceAssignment_6_1() { return cCouleurPoliceAssignment_6_1; }

		//EString
		public RuleCall getCouleurPoliceEStringParserRuleCall_6_1_0() { return cCouleurPoliceEStringParserRuleCall_6_1_0; }

		//("taillePolice : " taillePolice=EInt)?
		public Group getGroup_7() { return cGroup_7; }

		//"taillePolice : "
		public Keyword getTaillePoliceKeyword_7_0() { return cTaillePoliceKeyword_7_0; }

		//taillePolice=EInt
		public Assignment getTaillePoliceAssignment_7_1() { return cTaillePoliceAssignment_7_1; }

		//EInt
		public RuleCall getTaillePoliceEIntParserRuleCall_7_1_0() { return cTaillePoliceEIntParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class PageInterneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PageInterne");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageInterneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTitrePageKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTitrePageAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTitrePageEStringParserRuleCall_2_1_0 = (RuleCall)cTitrePageAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTexteKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTexteAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTexteEStringParserRuleCall_3_1_0 = (RuleCall)cTexteAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypesTypesParserRuleCall_4_1_0 = (RuleCall)cTypesAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLiensKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cLiensAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cLiensLiensParserRuleCall_5_1_0 = (RuleCall)cLiensAssignment_5_1.eContents().get(0);
		private final Keyword cPhotoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPhotoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPhotoPhotoParserRuleCall_7_0 = (RuleCall)cPhotoAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//PageInterne:
		//	"PageInterne" "{" ("titrePage : " titrePage=EString)? ("texte : " texte=EString)? ("types : " types=Types)?
		//	("liens : " liens=Liens)? "photo : " photo=Photo "}";
		public ParserRule getRule() { return rule; }

		//"PageInterne" "{" ("titrePage : " titrePage=EString)? ("texte : " texte=EString)? ("types : " types=Types)? ("liens : "
		//liens=Liens)? "photo : " photo=Photo "}"
		public Group getGroup() { return cGroup; }

		//"PageInterne"
		public Keyword getPageInterneKeyword_0() { return cPageInterneKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("titrePage : " titrePage=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"titrePage : "
		public Keyword getTitrePageKeyword_2_0() { return cTitrePageKeyword_2_0; }

		//titrePage=EString
		public Assignment getTitrePageAssignment_2_1() { return cTitrePageAssignment_2_1; }

		//EString
		public RuleCall getTitrePageEStringParserRuleCall_2_1_0() { return cTitrePageEStringParserRuleCall_2_1_0; }

		//("texte : " texte=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"texte : "
		public Keyword getTexteKeyword_3_0() { return cTexteKeyword_3_0; }

		//texte=EString
		public Assignment getTexteAssignment_3_1() { return cTexteAssignment_3_1; }

		//EString
		public RuleCall getTexteEStringParserRuleCall_3_1_0() { return cTexteEStringParserRuleCall_3_1_0; }

		//("types : " types=Types)?
		public Group getGroup_4() { return cGroup_4; }

		//"types : "
		public Keyword getTypesKeyword_4_0() { return cTypesKeyword_4_0; }

		//types=Types
		public Assignment getTypesAssignment_4_1() { return cTypesAssignment_4_1; }

		//Types
		public RuleCall getTypesTypesParserRuleCall_4_1_0() { return cTypesTypesParserRuleCall_4_1_0; }

		//("liens : " liens=Liens)?
		public Group getGroup_5() { return cGroup_5; }

		//"liens : "
		public Keyword getLiensKeyword_5_0() { return cLiensKeyword_5_0; }

		//liens=Liens
		public Assignment getLiensAssignment_5_1() { return cLiensAssignment_5_1; }

		//Liens
		public RuleCall getLiensLiensParserRuleCall_5_1_0() { return cLiensLiensParserRuleCall_5_1_0; }

		//"photo : "
		public Keyword getPhotoKeyword_6() { return cPhotoKeyword_6; }

		//photo=Photo
		public Assignment getPhotoAssignment_7() { return cPhotoAssignment_7; }

		//Photo
		public RuleCall getPhotoPhotoParserRuleCall_7_0() { return cPhotoPhotoParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class TypesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Types");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypesAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cGrasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cGrasGrasKeyword_1_0 = (Keyword)cGrasAssignment_1.eContents().get(0);
		private final Assignment cItaliqueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cItaliqueItaliqueKeyword_2_0 = (Keyword)cItaliqueAssignment_2.eContents().get(0);
		private final Keyword cTypesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Types:
		//	{Types} gras?="gras"? italique?="italique"? "Types";
		public ParserRule getRule() { return rule; }

		//{Types} gras?="gras"? italique?="italique"? "Types"
		public Group getGroup() { return cGroup; }

		//{Types}
		public Action getTypesAction_0() { return cTypesAction_0; }

		//gras?="gras"?
		public Assignment getGrasAssignment_1() { return cGrasAssignment_1; }

		//"gras"
		public Keyword getGrasGrasKeyword_1_0() { return cGrasGrasKeyword_1_0; }

		//italique?="italique"?
		public Assignment getItaliqueAssignment_2() { return cItaliqueAssignment_2; }

		//"italique"
		public Keyword getItaliqueItaliqueKeyword_2_0() { return cItaliqueItaliqueKeyword_2_0; }

		//"Types"
		public Keyword getTypesKeyword_3() { return cTypesKeyword_3; }
	}

	public class LiensElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Liens");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLiensAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLiensKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFichierKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFichierAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFichierEStringParserRuleCall_3_1_0 = (RuleCall)cFichierAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAdresseWebKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAdresseWebAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAdresseWebEStringParserRuleCall_4_1_0 = (RuleCall)cAdresseWebAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPageInterneKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPageInterneAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPageInterneEStringParserRuleCall_5_1_0 = (RuleCall)cPageInterneAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Liens:
		//	{Liens} "Liens" "{" ("fichier : " fichier=EString)? ("adresseWeb : " adresseWeb=EString)? ("pageInterne : "
		//	pageInterne=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Liens} "Liens" "{" ("fichier : " fichier=EString)? ("adresseWeb : " adresseWeb=EString)? ("pageInterne : "
		//pageInterne=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Liens}
		public Action getLiensAction_0() { return cLiensAction_0; }

		//"Liens"
		public Keyword getLiensKeyword_1() { return cLiensKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("fichier : " fichier=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"fichier : "
		public Keyword getFichierKeyword_3_0() { return cFichierKeyword_3_0; }

		//fichier=EString
		public Assignment getFichierAssignment_3_1() { return cFichierAssignment_3_1; }

		//EString
		public RuleCall getFichierEStringParserRuleCall_3_1_0() { return cFichierEStringParserRuleCall_3_1_0; }

		//("adresseWeb : " adresseWeb=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"adresseWeb : "
		public Keyword getAdresseWebKeyword_4_0() { return cAdresseWebKeyword_4_0; }

		//adresseWeb=EString
		public Assignment getAdresseWebAssignment_4_1() { return cAdresseWebAssignment_4_1; }

		//EString
		public RuleCall getAdresseWebEStringParserRuleCall_4_1_0() { return cAdresseWebEStringParserRuleCall_4_1_0; }

		//("pageInterne : " pageInterne=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"pageInterne : "
		public Keyword getPageInterneKeyword_5_0() { return cPageInterneKeyword_5_0; }

		//pageInterne=EString
		public Assignment getPageInterneAssignment_5_1() { return cPageInterneAssignment_5_1; }

		//EString
		public RuleCall getPageInterneEStringParserRuleCall_5_1_0() { return cPageInterneEStringParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class PhotoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Photo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPhotoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPhotoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTailleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTailleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTailleEFloatParserRuleCall_3_1_0 = (RuleCall)cTailleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cExtensionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cExtensionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cExtensionEStringParserRuleCall_4_1_0 = (RuleCall)cExtensionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNomKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNomAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cNomEStringParserRuleCall_5_1_0 = (RuleCall)cNomAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Photo:
		//	{Photo} "Photo" "{" ("taille : " taille=EFloat)? ("extension : " extension=EString)? ("nom : " nom=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Photo} "Photo" "{" ("taille : " taille=EFloat)? ("extension : " extension=EString)? ("nom : " nom=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Photo}
		public Action getPhotoAction_0() { return cPhotoAction_0; }

		//"Photo"
		public Keyword getPhotoKeyword_1() { return cPhotoKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("taille : " taille=EFloat)?
		public Group getGroup_3() { return cGroup_3; }

		//"taille : "
		public Keyword getTailleKeyword_3_0() { return cTailleKeyword_3_0; }

		//taille=EFloat
		public Assignment getTailleAssignment_3_1() { return cTailleAssignment_3_1; }

		//EFloat
		public RuleCall getTailleEFloatParserRuleCall_3_1_0() { return cTailleEFloatParserRuleCall_3_1_0; }

		//("extension : " extension=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"extension : "
		public Keyword getExtensionKeyword_4_0() { return cExtensionKeyword_4_0; }

		//extension=EString
		public Assignment getExtensionAssignment_4_1() { return cExtensionAssignment_4_1; }

		//EString
		public RuleCall getExtensionEStringParserRuleCall_4_1_0() { return cExtensionEStringParserRuleCall_4_1_0; }

		//("nom : " nom=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"nom : "
		public Keyword getNomKeyword_5_0() { return cNomKeyword_5_0; }

		//nom=EString
		public Assignment getNomAssignment_5_1() { return cNomAssignment_5_1; }

		//EString
		public RuleCall getNomEStringParserRuleCall_5_1_0() { return cNomEStringParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_4() { return cGroup_4; }

		//"E" | "e"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"E"
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }

		//"e"
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	
	private final PagePrincipaleElements pPagePrincipale;
	private final ContactElements pContact;
	private final RubriquesElements pRubriques;
	private final FichiersElements pFichiers;
	private final ConfigurationPageElements pConfigurationPage;
	private final PageInterneElements pPageInterne;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final TypesElements pTypes;
	private final LiensElements pLiens;
	private final PhotoElements pPhoto;
	private final EBooleanElements pEBoolean;
	private final EFloatElements pEFloat;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPagePrincipale = new PagePrincipaleElements();
		this.pContact = new ContactElements();
		this.pRubriques = new RubriquesElements();
		this.pFichiers = new FichiersElements();
		this.pConfigurationPage = new ConfigurationPageElements();
		this.pPageInterne = new PageInterneElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pTypes = new TypesElements();
		this.pLiens = new LiensElements();
		this.pPhoto = new PhotoElements();
		this.pEBoolean = new EBooleanElements();
		this.pEFloat = new EFloatElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.siteWeb.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//PagePrincipale:
	//	"PagePrincipale" "{" "configurationPage" configurationPage=ConfigurationPage "contacts" "{" contacts+=Contact (","
	//	contacts+=Contact)* "}" "pages" "{" pages+=PageInterne ("," pages+=PageInterne)* "}" ("rubriques"
	//	rubriques=Rubriques)? ("fichiers" "{" fichiers+=Fichiers ("," fichiers+=Fichiers)* "}")? "}";
	public PagePrincipaleElements getPagePrincipaleAccess() {
		return pPagePrincipale;
	}
	
	public ParserRule getPagePrincipaleRule() {
		return getPagePrincipaleAccess().getRule();
	}

	//Contact:
	//	{Contact} "Contact" "{" ("nom : " nom=EString)? ("prenom : " prenom=EString)? ("adresse : " adresse=EString)?
	//	("mail : " mail=EString+ "@" EString+ "." EString EString EString) ("telephone : " telephone=EString)? "}";
	public ContactElements getContactAccess() {
		return pContact;
	}
	
	public ParserRule getContactRule() {
		return getContactAccess().getRule();
	}

	//Rubriques:
	//	{Rubriques} "Rubriques" "{" ("texte : " texte=EString)? ("lien : " lien=EString)? "}";
	public RubriquesElements getRubriquesAccess() {
		return pRubriques;
	}
	
	public ParserRule getRubriquesRule() {
		return getRubriquesAccess().getRule();
	}

	//Fichiers:
	//	{Fichiers} "Fichiers" "{" ("type : " type=EString)? ("taille : " taille=EInt)? ("nom : " nom=EString)?
	//	("emplacement : " emplacement=EString)? "}";
	public FichiersElements getFichiersAccess() {
		return pFichiers;
	}
	
	public ParserRule getFichiersRule() {
		return getFichiersAccess().getRule();
	}

	//ConfigurationPage:
	//	{ConfigurationPage} "ConfigurationPage" "{" ("couleurFond : " couleurFond=EString)? ("titreSite : "
	//	titreSite=EString)? ("auteurs : " auteurs=EString)? ("couleurPolice : " couleurPolice=EString)? ("taillePolice : "
	//	taillePolice=EInt)? "}";
	public ConfigurationPageElements getConfigurationPageAccess() {
		return pConfigurationPage;
	}
	
	public ParserRule getConfigurationPageRule() {
		return getConfigurationPageAccess().getRule();
	}

	//PageInterne:
	//	"PageInterne" "{" ("titrePage : " titrePage=EString)? ("texte : " texte=EString)? ("types : " types=Types)?
	//	("liens : " liens=Liens)? "photo : " photo=Photo "}";
	public PageInterneElements getPageInterneAccess() {
		return pPageInterne;
	}
	
	public ParserRule getPageInterneRule() {
		return getPageInterneAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//Types:
	//	{Types} gras?="gras"? italique?="italique"? "Types";
	public TypesElements getTypesAccess() {
		return pTypes;
	}
	
	public ParserRule getTypesRule() {
		return getTypesAccess().getRule();
	}

	//Liens:
	//	{Liens} "Liens" "{" ("fichier : " fichier=EString)? ("adresseWeb : " adresseWeb=EString)? ("pageInterne : "
	//	pageInterne=EString)? "}";
	public LiensElements getLiensAccess() {
		return pLiens;
	}
	
	public ParserRule getLiensRule() {
		return getLiensAccess().getRule();
	}

	//Photo:
	//	{Photo} "Photo" "{" ("taille : " taille=EFloat)? ("extension : " extension=EString)? ("nom : " nom=EString)? "}";
	public PhotoElements getPhotoAccess() {
		return pPhoto;
	}
	
	public ParserRule getPhotoRule() {
		return getPhotoAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EFloat returns ecore::EFloat:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
