/**
 * generated by Xtext
 */
package org.xtext.example.siteWeb.serializer;

import org.xtext.example.siteWeb.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
