/**
 * generated by Xtext
 */
package org.xtext.example.siteWeb.serializer;

import org.xtext.example.siteWeb.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
